---
- hosts: all
  become: true
  tasks:

  - name: Install Apache2 package
    yum:
      name: httpd
      state: latest

  - name: Start Apache2 service
    service:
      name: httpd
      state: started
      enabled: true